### ISSUE TITLE
TOC with bad redirect link

### ISSUE THREAD

**Issue by H4ad** [ada-url/website#24]
The following code:

https://github.com/ada-url/website/blob/e5537a22b1c2b7cd1c0615d1208d223ed32be36a/components/toc.tsx#L89C15-L98

Is causing a constant page refresh after click in the TOC link:

https://github.com/ada-url/website/assets/12551007/1fe280e7-0907-4d11-89ba-a0e17e8806fc

The fix is to try to generate the final URL without `index.html`, just `#hash`.

**Comment by anonrig** [comment]
Does this happen in the new website? Ref: https://ada-url.vercel.app/docs/clients/cpp

**Comment by H4ad** [comment]
Oh, I didn't know that had more than one site, but no, the new site is redirecting with no page refresh.
