### ISSUE TITLE
The playground does not report errors

### ISSUE THREAD

**Issue by lemire** [ada-url/website#32]
<img width="1369" alt="Capture d’écran, le 2023-06-15 à 15 22 16" src="https://github.com/ada-url/website/assets/391987/187ccbb8-69eb-4e00-a3c6-2a61afac3e36">

Try parsing "http://RuPaul's Drag Race All Stars 7 Winners Cast on This Season's". I would expect an error. I get no reaction from the page.

**Comment by AugustinMauroy** [comment]
It isn't working because it's an invalide url ?

**Comment by lemire** [comment]
Well. It should tell us that it is not valid.

**Comment by anonrig** [comment]
This was an easy fix. I committed to the `main` branch.
