### ISSUE TITLE
Python documentation

### ISSUE THREAD

**Issue by anonrig** [ada-url/website#4]
We should improve the Python client documentation

**Comment by AugustinMauroy** [comment]
Should we migrate https://ada-url.readthedocs.io/en/latest/ on this website ?

**Comment by anonrig** [comment]
It depends on @bbayles. I'm fine with their pull request #20.

**Comment by AugustinMauroy** [comment]
It's can be on other pr

**Comment by anonrig** [comment]
If we migrate, this means that every client of Ada needs to update the website for every package change. I prefer not to make a burden for @lemire on Go, @bbayles on Python and me on Rust client to do this.
